### ISSUE TITLE
[Model] Remove the need of 'new' in branches for a trigger

### ISSUE THREAD

**Issue by mandel-macaque** [sharpliner/sharpliner#20]
In the sample code we have:
```csharp
Pr = new DetailedPrTrigger()
{
    Branches = new()
    {
        Include = { "main", "xcode/*" }
    }
},
```

I am very lazy, can I remove the need of 'new'?
```csharp
Pr = new DetailedPrTrigger()
{
    Branches =
    {
        Include = { "main", "xcode/*" }
    }
},
```

Since the code generated does not need to be efficient, we just serialise, I don't mind putting some pressure in the GC and have an object by default and later remove it. Will this complicate the serialisation, definitely, but we are here for that :)

**Comment by premun** [comment]
@mandel-macaque there is another trigger we can use with the same effect:
```csharp
Pr = new BranchPrTrigger("main", "xcode/*"),
```

The reason there is this `new()` is that the detailed trigger has `Include` and `Exclude` properties.

I used the detailed one so that the YAML matches the one we have in the real pipeline so that the diff is the same but it would have the same effect to use the shorter one.

**Comment by premun** [comment]
Actually, this could be done as well

**Comment by premun** [comment]
This was done in #29
